import React,{useEffect,useState} from 'react';
import "./style.css";
import {marked} from 'marked'; import DOMPurify from 'dompurify'; import {api} from './services/api'; import type {Session,Message,Source} from './types'; import './style.css';
export default function App(){const [sessions,setSessions]=useState<Session[]>([]),[sid,setSid]=useState(''),[msgs,setMsgs]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[artifact,setArtifact]=useState<any>(null),[model,setModel]=useState<any>(null),[error,setError]=useState('');
 const refresh=async()=>{try{const s=await api.sessions();setSessions(s);if(!sid&&s[0])setSid(s[0].id);setModel(await api.model())}catch(e:any){setError(e.message)}};
 useEffect(()=>{refresh()},[]); useEffect(()=>{if(sid)api.messages(sid).then(setMsgs).catch(e=>setError(e.message))},[sid]);
 async function newChat(){const s=await api.create();setSessions(x=>[s,...x]);setSid(s.id);setMsgs([]);setArtifact(null)}
 async function send(){if(!input.trim()||!sid||busy)return;const text=input.trim();setInput('');setBusy(true);setError('');setMsgs(x=>[...x,{id:crypto.randomUUID(),role:'user',content:text,created_at:new Date().toISOString()}]);try{const r=await api.ask(sid,text);setMsgs(x=>[...x,{id:crypto.randomUUID(),role:'assistant',content:r.answer,created_at:new Date().toISOString(),metadata:{sources:r.sources}}]);if(r.artifact_id)setArtifact(await api.artifact(r.artifact_id))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="app"><header><b>Lenny Growth Assistant</b><span>{model?.provider||'model'} · {model?.model||''} <i className={model?.available?'on':'off'}>●</i></span></header><main><aside><button onClick={newChat}>＋ New Chat</button>{sessions.map(s=><button className={s.id===sid?'active':''} onClick={()=>setSid(s.id)} key={s.id}>{s.title}</button>)}</aside><section className="chat"><div className="messages">{msgs.length===0&&<div className="empty">Ask a product or growth question based on Lenny's Podcast.</div>}{msgs.map(m=><div className={'msg '+m.role} key={m.id}><div dangerouslySetInnerHTML={{__html:DOMPurify.sanitize(marked.parse(m.content) as string)}}/>{m.role==='assistant'&&m.metadata?.sources?.length?<Sources sources={m.metadata.sources}/>:null}</div>)}{busy&&<div className="msg assistant">Searching transcripts and generating answer…</div>}</div><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask a product or growth question..."/><button onClick={send}>Send</button></div>{error&&<div className="error">{error}</div>}</section><section className="artifact"><h3>Artifact Viewer</h3>{artifact?<><h4>{artifact.title}</h4>{artifact.type==='html'?<iframe sandbox="" srcDoc={DOMPurify.sanitize(artifact.content,{USE_PROFILES:{html:true}})}/>:<div dangerouslySetInnerHTML={{__html:DOMPurify.sanitize(marked.parse(artifact.content) as string)}}/>}</>:<div className="empty">Artifacts generated from the conversation appear here.</div>}</section></main></div>}
function Sources({sources}:{sources:Source[]}){return <div className="sources"><b>Sources</b>{sources.map((s,i)=><a key={i} href={s.source_url} target="_blank" rel="noreferrer">{s.title} · {Math.round(s.relevance*100)}%</a>)}</div>}
